---
apiVersion: v1
kind: Secret
metadata:
  name: quinoa-wind-turbine-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/quinoa-wind-turbine-gitops